### PR TITLE
version 23.02.1: Add inverse exp

### PR DESCRIPTION
**Pull request by mgross**
### New Features
- Model updates:
  - Add inverse exponents as features. Now one can add x^-1, x^-2,.. as potential modelling features
  - Model averaging added. Now models can be averaged by a criterion (AIC, AICc, WAIC, logLik, BIC and Loo)
  - Imputation of missing values added (multiple imputation via the mice package)

- App integration
  - new slider _Max inverse exponent_ (1) 

image

  - new checkbox _Impute missing values ... _ (2)
  - new UI _Create model average_ (3)

image

### CODE REVIEW

**Comment by arunge** [comment]
I assume, https://github.com/Pandora-IsoMemo/bmsc/pull/1 must be merged first before I review here. Checks are also failing, maybe because of this...

**Comment by mgross** [comment]
@arunge: Yes

**Review by arunge — APPROVED** [review]
I have added comments to the news.md and removed some warnings. I only tested with example data, seems to work. :heavy_check_mark:

**Comment by arunge** [comment]
@mgross I am merging your feature "add inverse exp" into the app now.

**Pull request merged**
